name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo, pdo_pgsql

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Copy environment file
        run: cp .env.test .env

      - name: Run tests
        run: php bin/phpunit --coverage-clover=clover.xml --coverage-text

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./clover.xml

      - name: PHPStan
        run: php vendor/bin/phpstan analyse --no-progress

      - name: PHP CS Fixer (dry run)
        run: php vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Security Checker
        run: php vendor/bin/security-checker security:check || true


